# Scikit-Learn Python Library


***

This notebook is a overview of the [sckit-learn Python libray](https://scikit-learn.org/stable/): a free software machine learning library for the [Python](https://www.python.org/) programming language. 
It also supports supervised and unsupervised learning and provides various tools for model fitting, data preprocessing, model selection and evaluation, and many other utilities.

<br>

## An introduction to machine learning with scikit-learn
https://scikit-learn.org/stable/tutorial/basic/tutorial.html

In [1]:
import sklearn.datasets as datasets

In [2]:
iris = datasets.load_iris()

In [3]:
digits = datasets.load_digits()

In [4]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [5]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [7]:
from sklearn import svm

In [8]:
clf = svm.SVC(gamma=0.001, C=100.)

In [9]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, gamma=0.001)

In [10]:
clf.predict(digits.data[-1:])

array([8])

<br>

## Different Types of Scikit-Learn Algorithms

***

The two main categories of Machine Learning Algorithms are Supervised learning and Unsupervised learning.

### Supervised Learning
Supervised learning is where an algorithm is trained on input data that has been labeled for a particular output based on example input-output pairs that exist in the algorithm.
This basically means the computer is already aware of what the possible output will be of the raw input being processed.

<img src="https://cdn.datafloq.com/cms/2018/01/23/supervised-learning.png" alt="Supervised-Learning" width="600">

Click [here](https://datafloq.com/read/machine-learning-explained-understanding-learning/4478) for more information about the image.

### UnSupervised Learning
Unsupervised learning uses algorithms to analyze raw input data, without any pre-assigned labels. It works by discovering patterns and differences in the data set.

<img src="https://www.gong-jj.com/images/ml-unsup/unsup_header.png" alt="Supervised-Learning" width="600">

Click [here](https://www.gong-jj.com/ul/) for more information about the image.

<br>

## Supervised Learning Algorithms

***

## Classification: Analysis on The Wine Quality Data Set 
![Wine Quality Data Set](https://archive.ics.uci.edu/ml/assets/MLimages/Large186.jpg)

[Wine Quality Data Set](https://archive.ics.uci.edu/ml/datasets/Wine+Quality) available at the [UC Irvine Machine Learning](https://archive.ics.uci.edu/ml/index.php)
***

## Setup

In [11]:
# Numerical arrays.
import numpy as np

# Data frames.
import pandas as pd

# Plotting.
import matplotlib.pyplot as plt

# Logistic regression.
import sklearn.linear_model as lm

# K nearest neaighbours.
import sklearn.neighbors as nei

# Helper functions.
import sklearn.model_selection as mod

# Fancier, statistical plots.
import seaborn as sns

In [12]:
# Standard plot size.
plt.rcParams['figure.figsize'] = (15, 10)

# Standard colour scheme.
plt.style.use('ggplot')

### The Red Wine Quality Dataset

In [13]:
# Load the Wine Quality data set from a URL.
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=';')

In [14]:
df.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

In [15]:
# Have a look at the data.
df.shape

(1599, 12)

In [16]:
# Summary statistics.
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [17]:
# Data Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [18]:
# Feature Relationships
df.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.256131     0.671703   
volatile acidity          -0.256131          1.000000    -0.552496   
citric acid                0.671703         -0.552496     1.000000   
residual sugar             0.114777          0.001918     0.143577   
chlorides                  0.093705          0.061298     0.203823   
free sulfur dioxide       -0.153794         -0.010504    -0.060978   
total sulfur dioxide      -0.113181          0.076470     0.035533   
density                    0.668047          0.022026     0.364947   
pH                        -0.682978          0.234937    -0.541904   
sulphates                  0.183006         -0.260987     0.312770   
alcohol                   -0.061668         -0.202288     0.109903   
quality                    0.124052         -0.390558     0.226373   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.114777   0.093705            -0.153794   
volatile acidity            0.001918   0.061298            -0.010504   
citric acid                 0.143577   0.203823            -0.060978   
residual sugar              1.000000   0.055610             0.187049   
chlorides                   0.055610   1.000000             0.005562   
free sulfur dioxide         0.187049   0.005562             1.000000   
total sulfur dioxide        0.203028   0.047400             0.667666   
density                     0.355283   0.200632            -0.021946   
pH                         -0.085652  -0.265026             0.070377   
sulphates                   0.005527   0.371260             0.051658   
alcohol                     0.042075  -0.221141            -0.069408   
quality                     0.013732  -0.128907            -0.050656   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.113181  0.668047 -0.682978   0.183006   
volatile acidity                  0.076470  0.022026  0.234937  -0.260987   
citric acid                       0.035533  0.364947 -0.541904   0.312770   
residual sugar                    0.203028  0.355283 -0.085652   0.005527   
chlorides                         0.047400  0.200632 -0.265026   0.371260   
free sulfur dioxide               0.667666 -0.021946  0.070377   0.051658   
total sulfur dioxide              1.000000  0.071269 -0.066495   0.042947   
density                           0.071269  1.000000 -0.341699   0.148506   
pH                               -0.066495 -0.341699  1.000000  -0.196648   
sulphates                         0.042947  0.148506 -0.196648   1.000000   
alcohol                          -0.205654 -0.496180  0.205633   0.093595   
quality                          -0.185100 -0.174919 -0.057731   0.251397   

                       alcohol   quality  
fixed acidity        -0.061668  0.124052  
volatile acidity     -0.202288 -0.390558  
citric acid           0.109903  0.226373  
residual sugar        0.042075  0.013732  
chlorides            -0.221141 -0.128907  
free sulfur dioxide  -0.069408 -0.050656  
total sulfur dioxide -0.205654 -0.185100  
density              -0.496180 -0.174919  
pH                    0.205633 -0.057731  
sulphates             0.093595  0.251397  
alcohol               1.000000  0.476166  
quality               0.476166  1.000000

In [19]:
# Assign Specific Labels to Wine Quality
bins = (0, 4, 7, 10)
labels = ["bad", "medium", "good"]
df['quality'] = pd.cut(x = df['quality'], bins = bins, labels = labels)

In [20]:
df['quality'].value_counts()

medium    1518
bad         63
good        18
Name: quality, dtype: int64

### Visualise Data Set

In [ ]:
# Scatter plots and kdes.
sns.pairplot(df, hue='quality', palette = "Set2");

### Two Dimensions Data Representation

In [ ]:
# New figure.
fig, ax = plt.subplots()

# Scatter plot.
ax.plot(df['alcohol'], df['pH'], '.')

# Set axis labels.
ax.set_xlabel('Alcohol');
ax.set_ylabel('Ph');

In [ ]:
# Seaborn is great for creating complex plots with one command.
sns.lmplot(x='alcohol', y='pH', hue='quality', data=df, fit_reg=False, height=10, aspect=1.5, palette="Set2")

In [ ]:
# Count Plot 
sns.countplot(x='quality',data=df, palette="Set2")

In [ ]:
# Heatmap Visulation Dataset
plt.figure(figsize=(12,12))
sns.heatmap(data=df.corr(),annot=True,cmap="flare")
plt.show()

In [ ]:
# Segregate the data.
bad = df[df['quality'] == 'bad']
medium = df[df['quality'] == 'medium']
good = df[df['quality'] == 'good']

# New plot.
fig, ax = plt.subplots()

# Scatter plots.
ax.scatter(bad['alcohol'], bad['pH'], label='Bad')
ax.scatter(medium['alcohol'], medium['pH'], label='Medium')
ax.scatter(good['alcohol'], good['pH'], label='Good')


# Show the legend.
ax.set_xlabel('Alcohol')
ax.set_ylabel('pH')
ax.legend();

In [ ]:
# How the segregation works.
df['quality'] == 'bad'

In [ ]:
df[df['quality'] == 'bad'].head()

### Using groupby()

In [ ]:
# New plot.
fig, ax = plt.subplots()

# Using pandas groupby().
for quality, data in df.groupby('quality'):
    ax.scatter(data['alcohol'], data['pH'], label=quality)

# Show the legend.
ax.set_xlabel('Alcohol')
ax.set_ylabel('pH')
ax.legend();

In [ ]:
# Group by typically takes a categorical variable.
x = df.groupby('quality')
x

In [ ]:
# Pivot tables.
x.mean()

In [ ]:
# Looping through groupby().
for i, j in x:
    print()
    print(f"i is: '{i}'")
    print(f"j is:\n{j[:3]}")
    print()

## Test and Train Split

In [ ]:
# Split the data frame in two.
train, test = mod.train_test_split(df)

In [ ]:
# Show some training data.
train.head()

In [ ]:
# The indices of the train array.
train.index

In [ ]:
# Show some testing data.
test.head()

In [ ]:
test.index.size

## Two Dimensions: Test Train Split

In [ ]:
# Segregate the data.
bad = df[df['quality'] == 'bad']
medium = df[df['quality'] == 'medium']
good = df[df['quality'] == 'good']

# New plot.
fig, ax = plt.subplots()

# Scatter plots.
ax.scatter(bad['alcohol'], bad['pH'], marker='o' , label='Bad')
ax.scatter(medium['alcohol'], medium['pH'], marker='o', label='Medium')
ax.scatter(good['alcohol'], good['pH'], marker='o', label='Good')

# Scatter plot for testing data.
ax.scatter(test['alcohol'], test['pH'], marker='x', label='Test data')

# Show the legend.
ax.set_xlabel('Alcohol')
ax.set_ylabel('pH')
ax.legend();

## Two Dimensions: Inputs and outputs

In [ ]:
# Give the inputs and outputs convenient names.
inputs, outputs = train[['alcohol', 'pH']], train['quality']

In [ ]:
# Peek at the inputs.
inputs.head()

In [ ]:
# Peek at the outputs.
outputs.head()

## Two Dimensions: Logistic regression
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
***

In [ ]:
# Create a new classifier.
lre = lm.LogisticRegression(random_state=0)

# Train the classifier on our data.
lre.fit(inputs, outputs)

In [ ]:
# Ask the classifier to classify the test data.
predictions = lre.predict(test[['alcohol', 'pH']])

In [ ]:
# Eyeball the misclassifications.
predictions == test['quality']

In [ ]:
# What proportion were correct?
lre.score(test[['alcohol', 'pH']], test['quality'])

## Two Dimensions: Misclassified

In [ ]:
# Append a column to the test data frame with the predictions.
test['predicted'] = predictions
test.head()

In [ ]:
# Show the misclassified data.
misclass = test[test['predicted'] != test['quality']]
misclass

In [ ]:
# Eyeball the descriptive statistics for the species.
train.groupby('quality').mean()

In [ ]:
# New plot.
fig, ax = plt.subplots()

# Plot the training data
for quality, data in df.groupby('quality'):
    ax.scatter(data['alcohol'], data['pH'], label=quality)
    
# Plot misclassified.
ax.scatter(misclass['alcohol'], misclass['pH'], s=200, facecolor='none', edgecolor='r', label='Misclassified')

# Show the legend.
ax.set_xlabel('Alcohol')
ax.set_ylabel('PH')
ax.legend();

## Seperating Bad Quality

From [Wikipedia](https://en.wikipedia.org/wiki/Logistic_regression):    ${L} = \log(b) \frac{p}{1-p} = \beta_0 + \beta_1 x_{1} + \beta_0 + \beta_2 x_{2}$


***

In [ ]:
# Give the inputs and outputs convenient names.
inputs = train[['alcohol', 'pH']]

# Set 'versicolor' and 'virginica' to 'other'.
outputs = train['quality'].apply(lambda x: x if x == 'bad' else 'other')

# Eyeball outputs
outputs.unique()

In [ ]:
# Create a new classifier.
lre = lm.LogisticRegression(random_state=0)

# Train the classifier on our data.
lre.fit(inputs, outputs)

In [ ]:
actual = test['quality'].apply(lambda x: x if x == 'bad' else 'other')

# What proportion were correct?
lre.score(test[['alcohol', 'pH']], actual)

## Using All Possible Inputs
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
***

In [ ]:
# Load the Wine Quality data set from a URL.
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=';')

In [ ]:
# Split the data frame in two.
train, test = mod.train_test_split(df)

In [ ]:
# Use all eleven possible inputs.
inputs, outputs = train[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']], train['quality']

In [ ]:
# Create a new classifier.
lre = lm.LogisticRegression(random_state=0)

# Train the classifier on our data.
lre.fit(inputs, outputs)

In [ ]:
# Ask the classifier to classify the test data.
predictions = lre.predict(test[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']])
predictions

In [ ]:
# Eyeball the misclassifications.
(predictions == test['quality']).value_counts()

In [ ]:
# What proportion were correct?
lre.score(test[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']], test['quality'])

## $\kappa$ Nearest Neighbours Classifier
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
***

In [ ]:
# Load the Wine Quality data set from a URL.
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=';')

In [ ]:
# Split the data frame in two.
train, test = mod.train_test_split(df)

In [ ]:
# Use all eleven possible inputs.
inputs, outputs = train[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']], train['quality']

In [ ]:
# Classifier.
knn = nei.KNeighborsClassifier()

In [ ]:
# Fit.
knn.fit(inputs, outputs)

In [ ]:
# Test.
knn.score(test[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']],  test['quality'])

In [ ]:
# Predict.
predictions = lre.predict(test[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']])
(predictions == test['quality']).value_counts()

In [ ]:
# The score is just the accuracy in this case.
(predictions == test['quality']).value_counts(normalize=True)

## Cross validation
https://scikit-learn.org/stable/modules/cross_validation.html
***

In [ ]:
knn = nei.KNeighborsClassifier()
scores = mod.cross_val_score(knn, df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']], df['quality'])
scores

In [ ]:
print(f"Mean: {scores.mean()} \t Standard Deviation: {scores.std()}")

In [ ]:
lre = lm.LogisticRegression(random_state=0)
scores = mod.cross_val_score(lre, df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']], df['quality'])
scores

In [ ]:
print(f"Mean: {scores.mean()} \t Standard Deviation: {scores.std()}")

## Basic Example of a Sckit-Learn Algorithm

***

## References
1. DataQuest "Scikit-learn Tutorial: Machine Learning in Python" https://www.dataquest.io/blog/sci-kit-learn-tutorial/

2. 

3. 

***

## End